server:
  port: 8888

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: IA WA post deployment functional test
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_CLIENT_SECRET:something}
azure:
  application-insights:
    instrumentation-key: ${wa.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  baseUrl: ${OPEN_ID_IDAM_URL:http://sidam-api}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://xui-webapp/oauth2/callback}
  scope: "openid profile roles"
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_TASK_MANAGEMENT_API:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_TASK_MANAGEMENT_API:wa_task_management_api}
  api:
    baseUrl: ${IDAM_URL:http://sidam-api}

camunda:
  url: ${CAMUNDA_URL:http://camunda-local-bpm/engine-rest}

role-assignment-service:
  url: ${ROLE_ASSIGNMENT_URL:http://am-role-assignment-service:4096}

logging:
  level:
    com.azure.*: OFF
    com.azure.core.amqp.implementation.*: OFF
    net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated: OFF
